# Generated by Django 2.0.2 on 2018-07-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('tuning_time', models.FloatField(default=0.0)),
                ('throughput', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
