# Generated by Django 2.0.2 on 2018-07-19 05:14

from django.db import migrations

def load_lead(apps, schema_editor):
    Lead = apps.get_model('core', 'Lead')
    lead_bohan = Lead(username='bohan', tuning_time=100.0, throughput=10001.1)
    lead_bohan.save()
    lead_siyuan = Lead(username='siyuan', tuning_time=100.1, throughput=1.0)
    lead_siyuan.save()

def delete_lead(apps, schema_editor):
    Lead = apps.get_model('core', 'Lead')
    Lead.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.RunPython(load_lead, delete_lead),
    ]
